title: Math Notebook
author:
  name: pinglamb

markdown: kramdown
kramdown:
  input: GFM

header_pages:
  - README.md

remote_theme: jekyll/minima
minima:
  skin: dark

plugins:
  - jekyll-remote-theme
