title: "&rho;&tau;"
author:
  name: pinglamb

# markdown: kramdown
# kramdown:
#   input: GFM

header_pages:
  - index.md

remote_theme: jekyll/minima
minima:
  skin: dark

plugins:
  - jekyll-remote-theme
